// Code generated by toolgen; DO NOT EDIT.
package fs

import (
	"fmt"
	"strings"
)

// FileWriteParams holds the typed parameters for this tool.
type FileWriteParams struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// ParseFileWriteParams reads typed parameter values from a map[string]interface{}.
func ParseFileWriteParams(args map[string]interface{}) (FileWriteParams, error) {
	var p FileWriteParams
	var errs []string

	if v, ok := args["path"]; ok && v != nil {
		val, err := convString("path", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Path = val
		}
	} else {
		errs = append(errs, "missing required parameter \"path\"")
	}

	if v, ok := args["content"]; ok && v != nil {
		val, err := convString("content", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Content = val
		}
	} else {
		errs = append(errs, "missing required parameter \"content\"")
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// FileWriteParamKeys returns the parameter names this tool consumes.
func FileWriteParamKeys() []string {
	return []string{
		"path",
		"content",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
