// Code generated by toolgen; DO NOT EDIT.
package fs

import (
	"fmt"
	"strings"
)

// FileSearchParams holds the typed parameters for this tool.
type FileSearchParams struct {
	Directory     string `json:"directory,omitempty"`
	Pattern       string `json:"pattern"`
	CaseSensitive bool   `json:"case_sensitive"`
}

// ParseFileSearchParams reads typed parameter values from a map[string]interface{}.
func ParseFileSearchParams(args map[string]interface{}) (FileSearchParams, error) {
	var p FileSearchParams
	var errs []string

	if v, ok := args["directory"]; ok && v != nil {
		val, err := convString("directory", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Directory = val
		}
	}

	if v, ok := args["pattern"]; ok && v != nil {
		val, err := convString("pattern", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Pattern = val
		}
	} else {
		errs = append(errs, "missing required parameter \"pattern\"")
	}

	if v, ok := args["case_sensitive"]; ok && v != nil {
		val, err := convBool("case_sensitive", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.CaseSensitive = val
		}
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// FileSearchParamKeys returns the parameter names this tool consumes.
func FileSearchParamKeys() []string {
	return []string{
		"directory",
		"pattern",
		"case_sensitive",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
