// Code generated by toolgen; DO NOT EDIT.
package fs

import (
	"fmt"
	"strings"
)

// FileCreateParams holds the typed parameters for this tool.
type FileCreateParams struct {
	Path    string `json:"path"`
	Content string `json:"content,omitempty"`
}

// ParseFileCreateParams reads typed parameter values from a map[string]interface{}.
func ParseFileCreateParams(args map[string]interface{}) (FileCreateParams, error) {
	var p FileCreateParams
	var errs []string

	if v, ok := args["path"]; ok && v != nil {
		val, err := convString("path", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Path = val
		}
	} else {
		errs = append(errs, "missing required parameter \"path\"")
	}

	if v, ok := args["content"]; ok && v != nil {
		val, err := convString("content", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Content = val
		}
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// FileCreateParamKeys returns the parameter names this tool consumes.
func FileCreateParamKeys() []string {
	return []string{
		"path",
		"content",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
