package state

import (
	"strings"
	"testing"
)

// TestAllKeysAreNonEmpty verifies that all key constants are non-empty strings.
func TestAllKeysAreNonEmpty(t *testing.T) {
	keys := []Key{
		KeyVerificationPolicy,
		KeyVerification,
		KeySuccessGate,
		KeyAssuranceClass,
		KeyExecutionWaiver,
		KeyWaiver,
		KeyRecoveryTrace,
		KeyBehaviorTrace,
		KeyArtifacts,
		KeyActionLog,
		KeyProofSurface,
		KeyFinalReport,
		KeyContextRuntime,
		KeySecurityRuntime,
		KeySharedContextRuntime,
		KeyCapabilityContractRuntime,
		KeyArchaeologyCapabilityRuntime,
		KeyDebugCapabilityRuntime,
		KeyChatCapabilityRuntime,
		KeyExecutorRuntime,
		KeyProviderRestore,
		KeyVerificationSummary,
		KeyReviewFindings,
		KeyRootCause,
		KeyRootCauseCandidates,
		KeyRegressionAnalysis,
		KeyPlanCandidates,
		KeyEditExecution,
		KeyEditIntent,
		KeyWorkflowID,
		KeyClassificationSource,
		KeyClassificationMeta,
		KeyPreClassifiedCapSeq,
		KeyCapabilitySequenceOperator,
		KeyUserRecipeSignals,
		KeyRetrievalPolicy,
		KeyContextLifecycle,
		KeySessionID,
		KeyDeferredIssues,
		KeyDeferralPlan,
		KeyInteractionScript,
		KeyRequiresEvidencePreMutation,
		KeySessionResumeContext,
		KeyArchaeoPhaseState,
		KeyCodeRevision,
		KeyResumeSemanticContext,
		KeyUnitOfWork,
		KeyUnitOfWorkID,
		KeyRootUnitOfWorkID,
		KeyUnitOfWorkHistory,
		KeyUnitOfWorkTransition,
		KeyEnvelope,
		KeyClassification,
		KeyModeResolution,
		KeyExecutionProfileSelection,
		KeyMode,
		KeyExecutionProfile,
		KeySemanticInputs,
		KeyResolvedExecutionPolicy,
		KeyExecutorDescriptor,
		KeyExecutionStatus,
		KeyCompiledExecution,
		KeyPipelineExplore,
		KeyPipelineAnalyze,
		KeyPipelinePlan,
		KeyPipelineCode,
		KeyPipelineVerify,
		KeyPipelineFinalOutput,
		KeyPipelineWorkflowRetrieval,
	}

	for _, key := range keys {
		if strings.TrimSpace(key) == "" {
			t.Errorf("key constant is empty")
		}
	}
}

// TestNoDuplicateKeys verifies that no two key constants share the same value.
func TestNoDuplicateKeys(t *testing.T) {
	keyMap := map[string]Key{
		KeyVerificationPolicy:           KeyVerificationPolicy,
		KeyVerification:                 KeyVerification,
		KeySuccessGate:                  KeySuccessGate,
		KeyAssuranceClass:               KeyAssuranceClass,
		KeyExecutionWaiver:              KeyExecutionWaiver,
		KeyWaiver:                       KeyWaiver,
		KeyRecoveryTrace:                KeyRecoveryTrace,
		KeyBehaviorTrace:                KeyBehaviorTrace,
		KeyArtifacts:                    KeyArtifacts,
		KeyActionLog:                    KeyActionLog,
		KeyProofSurface:                 KeyProofSurface,
		KeyFinalReport:                  KeyFinalReport,
		KeyContextRuntime:               KeyContextRuntime,
		KeySecurityRuntime:              KeySecurityRuntime,
		KeySharedContextRuntime:         KeySharedContextRuntime,
		KeyCapabilityContractRuntime:    KeyCapabilityContractRuntime,
		KeyArchaeologyCapabilityRuntime: KeyArchaeologyCapabilityRuntime,
		KeyDebugCapabilityRuntime:       KeyDebugCapabilityRuntime,
		KeyChatCapabilityRuntime:        KeyChatCapabilityRuntime,
		KeyExecutorRuntime:              KeyExecutorRuntime,
		KeyProviderRestore:              KeyProviderRestore,
		KeyVerificationSummary:          KeyVerificationSummary,
		KeyReviewFindings:               KeyReviewFindings,
		KeyRootCause:                    KeyRootCause,
		KeyRootCauseCandidates:          KeyRootCauseCandidates,
		KeyRegressionAnalysis:           KeyRegressionAnalysis,
		KeyPlanCandidates:               KeyPlanCandidates,
		KeyEditExecution:                KeyEditExecution,
		KeyEditIntent:                   KeyEditIntent,
		KeyWorkflowID:                   KeyWorkflowID,
		KeyClassificationSource:         KeyClassificationSource,
		KeyClassificationMeta:           KeyClassificationMeta,
		KeyPreClassifiedCapSeq:          KeyPreClassifiedCapSeq,
		KeyCapabilitySequenceOperator:   KeyCapabilitySequenceOperator,
		KeyUserRecipeSignals:            KeyUserRecipeSignals,
		KeyRetrievalPolicy:              KeyRetrievalPolicy,
		KeyContextLifecycle:             KeyContextLifecycle,
		KeySessionID:                    KeySessionID,
		KeyDeferredIssues:               KeyDeferredIssues,
		KeyDeferralPlan:                 KeyDeferralPlan,
		KeyInteractionScript:            KeyInteractionScript,
		KeyRequiresEvidencePreMutation:  KeyRequiresEvidencePreMutation,
		KeySessionResumeContext:         KeySessionResumeContext,
		KeyArchaeoPhaseState:            KeyArchaeoPhaseState,
		KeyCodeRevision:                 KeyCodeRevision,
		KeyResumeSemanticContext:        KeyResumeSemanticContext,
		KeyUnitOfWork:                   KeyUnitOfWork,
		KeyUnitOfWorkID:                 KeyUnitOfWorkID,
		KeyRootUnitOfWorkID:             KeyRootUnitOfWorkID,
		KeyUnitOfWorkHistory:            KeyUnitOfWorkHistory,
		KeyUnitOfWorkTransition:         KeyUnitOfWorkTransition,
		KeyEnvelope:                     KeyEnvelope,
		KeyClassification:               KeyClassification,
		KeyModeResolution:               KeyModeResolution,
		KeyExecutionProfileSelection:    KeyExecutionProfileSelection,
		KeyMode:                         KeyMode,
		KeyExecutionProfile:             KeyExecutionProfile,
		KeySemanticInputs:               KeySemanticInputs,
		KeyResolvedExecutionPolicy:      KeyResolvedExecutionPolicy,
		KeyExecutorDescriptor:           KeyExecutorDescriptor,
		KeyExecutionStatus:              KeyExecutionStatus,
		KeyCompiledExecution:            KeyCompiledExecution,
		KeyPipelineExplore:              KeyPipelineExplore,
		KeyPipelineAnalyze:              KeyPipelineAnalyze,
		KeyPipelinePlan:                 KeyPipelinePlan,
		KeyPipelineCode:                 KeyPipelineCode,
		KeyPipelineVerify:               KeyPipelineVerify,
		KeyPipelineFinalOutput:          KeyPipelineFinalOutput,
		KeyPipelineWorkflowRetrieval:    KeyPipelineWorkflowRetrieval,
	}

	// Check for duplicates by comparing length
	allKeys := []Key{
		KeyVerificationPolicy,
		KeyVerification,
		KeySuccessGate,
		KeyAssuranceClass,
		KeyExecutionWaiver,
		KeyWaiver,
		KeyRecoveryTrace,
		KeyBehaviorTrace,
		KeyArtifacts,
		KeyActionLog,
		KeyProofSurface,
		KeyFinalReport,
		KeyContextRuntime,
		KeySecurityRuntime,
		KeySharedContextRuntime,
		KeyCapabilityContractRuntime,
		KeyArchaeologyCapabilityRuntime,
		KeyDebugCapabilityRuntime,
		KeyChatCapabilityRuntime,
		KeyExecutorRuntime,
		KeyProviderRestore,
		KeyVerificationSummary,
		KeyReviewFindings,
		KeyRootCause,
		KeyRootCauseCandidates,
		KeyRegressionAnalysis,
		KeyPlanCandidates,
		KeyEditExecution,
		KeyEditIntent,
		KeyWorkflowID,
		KeyClassificationSource,
		KeyClassificationMeta,
		KeyPreClassifiedCapSeq,
		KeyCapabilitySequenceOperator,
		KeyUserRecipeSignals,
		KeyRetrievalPolicy,
		KeyContextLifecycle,
		KeySessionID,
		KeyDeferredIssues,
		KeyDeferralPlan,
		KeyInteractionScript,
		KeyRequiresEvidencePreMutation,
		KeySessionResumeContext,
		KeyArchaeoPhaseState,
		KeyCodeRevision,
		KeyResumeSemanticContext,
		KeyUnitOfWork,
		KeyUnitOfWorkID,
		KeyRootUnitOfWorkID,
		KeyUnitOfWorkHistory,
		KeyUnitOfWorkTransition,
		KeyEnvelope,
		KeyClassification,
		KeyModeResolution,
		KeyExecutionProfileSelection,
		KeyMode,
		KeyExecutionProfile,
		KeySemanticInputs,
		KeyResolvedExecutionPolicy,
		KeyExecutorDescriptor,
		KeyExecutionStatus,
		KeyCompiledExecution,
		KeyPipelineExplore,
		KeyPipelineAnalyze,
		KeyPipelinePlan,
		KeyPipelineCode,
		KeyPipelineVerify,
		KeyPipelineFinalOutput,
		KeyPipelineWorkflowRetrieval,
	}

	if len(allKeys) != len(keyMap) {
		t.Errorf("duplicate key values detected: have %d keys but map has %d entries", len(allKeys), len(keyMap))
	}
}

// TestKeyFormatInvariant verifies that all euclo keys start with "euclo." and all pipeline keys start with "pipeline.".
func TestKeyFormatInvariant(t *testing.T) {
	eucloKeys := []Key{
		KeyVerificationPolicy,
		KeyVerification,
		KeySuccessGate,
		KeyAssuranceClass,
		KeyExecutionWaiver,
		KeyWaiver,
		KeyRecoveryTrace,
		KeyBehaviorTrace,
		KeyArtifacts,
		KeyActionLog,
		KeyProofSurface,
		KeyFinalReport,
		KeyContextRuntime,
		KeySecurityRuntime,
		KeySharedContextRuntime,
		KeyCapabilityContractRuntime,
		KeyArchaeologyCapabilityRuntime,
		KeyDebugCapabilityRuntime,
		KeyChatCapabilityRuntime,
		KeyExecutorRuntime,
		KeyProviderRestore,
		KeyVerificationSummary,
		KeyReviewFindings,
		KeyRootCause,
		KeyRootCauseCandidates,
		KeyRegressionAnalysis,
		KeyPlanCandidates,
		KeyEditExecution,
		KeyEditIntent,
		KeyWorkflowID,
		KeyClassificationSource,
		KeyClassificationMeta,
		KeyPreClassifiedCapSeq,
		KeyCapabilitySequenceOperator,
		KeyUserRecipeSignals,
		KeyRetrievalPolicy,
		KeyContextLifecycle,
		KeySessionID,
		KeyDeferredIssues,
		KeyDeferralPlan,
		KeyInteractionScript,
		KeyRequiresEvidencePreMutation,
		KeySessionResumeContext,
		KeyArchaeoPhaseState,
		KeyCodeRevision,
		KeyResumeSemanticContext,
		KeyUnitOfWork,
		KeyUnitOfWorkID,
		KeyRootUnitOfWorkID,
		KeyUnitOfWorkHistory,
		KeyUnitOfWorkTransition,
		KeyEnvelope,
		KeyClassification,
		KeyModeResolution,
		KeyExecutionProfileSelection,
		KeyMode,
		KeyExecutionProfile,
		KeySemanticInputs,
		KeyResolvedExecutionPolicy,
		KeyExecutorDescriptor,
		KeyExecutionStatus,
		KeyCompiledExecution,
	}

	pipelineKeys := []Key{
		KeyPipelineExplore,
		KeyPipelineAnalyze,
		KeyPipelinePlan,
		KeyPipelineCode,
		KeyPipelineVerify,
		KeyPipelineFinalOutput,
		KeyPipelineWorkflowRetrieval,
	}

	for _, key := range eucloKeys {
		if !strings.HasPrefix(key, "euclo.") {
			t.Errorf("euclo key %q does not start with 'euclo.'", key)
		}
	}

	for _, key := range pipelineKeys {
		if !strings.HasPrefix(key, "pipeline.") {
			t.Errorf("pipeline key %q does not start with 'pipeline.'", key)
		}
	}
}
