// Code generated by toolgen; DO NOT EDIT.
package fs

import (
	"fmt"
	"strings"
)

// FileEditParams holds the typed parameters for this tool.
type FileEditParams struct {
	Path          string `json:"path"`
	OldString     string `json:"old_string"`
	NewString     string `json:"new_string"`
	ExpectedCount int    `json:"expected_count,omitempty"`
}

// ParseFileEditParams reads typed parameter values from a map[string]interface{}.
func ParseFileEditParams(args map[string]interface{}) (FileEditParams, error) {
	var p FileEditParams
	var errs []string

	if v, ok := args["path"]; ok && v != nil {
		val, err := convString("path", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Path = val
		}
	} else {
		errs = append(errs, "missing required parameter \"path\"")
	}

	if v, ok := args["old_string"]; ok && v != nil {
		val, err := convString("old_string", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.OldString = val
		}
	} else {
		errs = append(errs, "missing required parameter \"old_string\"")
	}

	if v, ok := args["new_string"]; ok && v != nil {
		val, err := convString("new_string", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.NewString = val
		}
	} else {
		errs = append(errs, "missing required parameter \"new_string\"")
	}

	if v, ok := args["expected_count"]; ok && v != nil {
		val, err := convInt64("expected_count", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.ExpectedCount = int(val)
		}
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// FileEditParamKeys returns the parameter names this tool consumes.
func FileEditParamKeys() []string {
	return []string{
		"path",
		"old_string",
		"new_string",
		"expected_count",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
