// Code generated by toolgen; DO NOT EDIT.
package fs

import (
	"fmt"
	"strings"
)

// FileListParams holds the typed parameters for this tool.
type FileListParams struct {
	Directory string `json:"directory,omitempty"`
	Pattern   string `json:"pattern,omitempty"`
}

// ParseFileListParams reads typed parameter values from a map[string]interface{}.
func ParseFileListParams(args map[string]interface{}) (FileListParams, error) {
	var p FileListParams
	var errs []string

	if v, ok := args["directory"]; ok && v != nil {
		val, err := convString("directory", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Directory = val
		}
	}

	if v, ok := args["pattern"]; ok && v != nil {
		val, err := convString("pattern", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Pattern = val
		}
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// FileListParamKeys returns the parameter names this tool consumes.
func FileListParamKeys() []string {
	return []string{
		"directory",
		"pattern",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
