// Code generated by toolgen; DO NOT EDIT.
package fs

import (
	"fmt"
	"strings"
)

// FileReadParams holds the typed parameters for this tool.
type FileReadParams struct {
	Path string `json:"path"`
}

// ParseFileReadParams reads typed parameter values from a map[string]interface{}.
func ParseFileReadParams(args map[string]interface{}) (FileReadParams, error) {
	var p FileReadParams
	var errs []string

	if v, ok := args["path"]; ok && v != nil {
		val, err := convString("path", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Path = val
		}
	} else {
		errs = append(errs, "missing required parameter \"path\"")
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// FileReadParamKeys returns the parameter names this tool consumes.
func FileReadParamKeys() []string {
	return []string{
		"path",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
