package config

import (
	"context"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/stretchr/testify/require"

	"codeburg.org/lexbit/relurpify/capability/ports"
	"codeburg.org/lexbit/relurpify/platform/fs"
	"codeburg.org/lexbit/relurpify/userconfig/tools/manifest"
	"codeburg.org/lexbit/relurpify/platform/tools/subprocess"
	"codeburg.org/lexbit/relurpify/userconfig/config/security"
)

const (
	testToolName       = "demo"
	testToolFamily     = "demo"
	testToolTrustClass = "builtin_trusted"
	testToolRiskClass  = "execute"
	testToolEffect     = "external_state"
	testFilesystemRead = "filesystem_read"
	testValueName      = "value"
	testStringType     = "string"
	testEchoBinary     = "echo"
	testFalseBinary    = "false"
)

type recordingRunner struct {
	request  ports.CommandRequest
	stdout   string
	stderr   string
	exitCode int
	err      error
}

func (r *recordingRunner) Run(_ context.Context, req ports.CommandRequest) (*ports.CommandResult, error) {
	r.request = req
	if r.err != nil {
		return nil, r.err
	}
	return &ports.CommandResult{
		Stdout:      r.stdout,
		Stderr:      r.stderr,
		ExitCode:    r.exitCode,
		StdoutBytes: int64(len(r.stdout)),
		StderrBytes: int64(len(r.stderr)),
	}, nil
}

func TestBuildRegistry_LocaltoolNameNotInManifests(t *testing.T) {
	defs := []*manifest.ToolManifest{
		{
			Name:        testToolName,
			Family:      testToolFamily,
			Description: testToolName,
			Execution: manifest.ToolManifestExecution{
				Backend:         manifest.ToolBackendSubprocess,
				Command:         &manifest.ToolManifestCommand{Base: []string{testToolName}},
				SupportsWorkdir: true,
			},
			Capability: manifest.ToolManifestCapability{
				TrustClass:  testToolTrustClass,
				RiskClass:   []string{testToolRiskClass},
				EffectClass: []string{testToolEffect},
			},
		},
	}

	_, err := BuildRegistry(defs, map[string]security.ToolPolicy{
		"missing": {Execute: "ask"},
	}, nil, nil)
	require.Error(t, err)
	require.Contains(t, err.Error(), "missing")
}

func TestBuildRegistry_GoNativeWithoutImplIsAllowed(t *testing.T) {
	defs := []*manifest.ToolManifest{
		{
			Name:        testToolName,
			Family:      testToolFamily,
			Description: testToolName,
			Execution: manifest.ToolManifestExecution{
				Backend:        manifest.ToolBackendGoNative,
				Implementation: testToolName,
			},
			Capability: manifest.ToolManifestCapability{
				TrustClass:  testToolTrustClass,
				RiskClass:   []string{"read_only"},
				EffectClass: []string{testFilesystemRead},
			},
		},
	}

	reg, err := BuildRegistry(defs, nil, nil, nil)
	require.NoError(t, err)
	manifest, ok := reg.LookupTool("demo")
	require.True(t, ok)
	require.Equal(t, testToolName, manifest.Name)
}

func TestBuildRegistry_SubprocessAutoGenerated(t *testing.T) {
	defs := []*manifest.ToolManifest{
		{
			Name:        testToolName,
			Family:      testToolFamily,
			Description: testToolName,
			Parameters: []manifest.ToolParameter{
				{Name: testValueName, Type: testStringType, Required: true},
			},
			Execution: manifest.ToolManifestExecution{
				Backend: manifest.ToolBackendSubprocess,
				Command: &manifest.ToolManifestCommand{Base: []string{testEchoBinary}},
			},
			Capability: manifest.ToolManifestCapability{
				TrustClass:  testToolTrustClass,
				RiskClass:   []string{testToolRiskClass},
				EffectClass: []string{testToolEffect},
			},
		},
	}

	reg, err := BuildRegistry(defs, map[string]security.ToolPolicy{
		testToolName: {Execute: "allow"},
	}, map[string]any{
		testToolName: stubTool{name: testToolName},
	}, nil)
	require.NoError(t, err)
	tool, ok := reg.Tool("demo")
	require.True(t, ok)
	require.Equal(t, stubTool{name: testToolName}, tool)
}

type stubTool struct {
	name string
}

func (t stubTool) Name() string                      { return t.name }
func (t stubTool) Description() string               { return t.name }
func (t stubTool) Category() string                  { return "demo" }
func (t stubTool) Parameters() []manifest.ToolParameter { return nil }
func (t stubTool) Execute(context.Context, map[string]any) (any, error) {
	return map[string]any{"success": true}, nil
}
func (t stubTool) IsAvailable(context.Context) bool   { return true }
func (t stubTool) Permissions() any                    { return map[string]any{} }
func (t stubTool) Tags() []string                     { return nil }

func TestGenerateSubprocessTool_ParameterSubstitution(t *testing.T) {
	def := &manifest.ToolManifest{
		Name:   testToolName,
		Family: testToolFamily,
		Parameters: []manifest.ToolParameter{
			{Name: testValueName, Type: testStringType, Required: true},
		},
		Execution: manifest.ToolManifestExecution{
			Backend: manifest.ToolBackendSubprocess,
			Command: &manifest.ToolManifestCommand{
				Base: []string{testEchoBinary},
				Args: []string{"${value}"},
			},
		},
		Capability: manifest.ToolManifestCapability{
			TrustClass:  testToolTrustClass,
			RiskClass:   []string{testToolRiskClass},
			EffectClass: []string{testToolEffect},
		},
	}
	runner := &recordingRunner{}
	tool := subprocess.NewTool(*def, runner)
	result, err := tool.Execute(context.Background(), map[string]any{testValueName: "hello"})
	require.NoError(t, err)
	require.True(t, result.Success)
	require.Equal(t, []string{testEchoBinary, "hello"}, runner.request.Args)
}

func TestGenerateSubprocessTool_ExitCodeInData(t *testing.T) {
	def := &manifest.ToolManifest{
		Name:   testToolName,
		Family: testToolFamily,
		Execution: manifest.ToolManifestExecution{
			Backend: manifest.ToolBackendSubprocess,
			Command: &manifest.ToolManifestCommand{
				Base: []string{testFalseBinary},
			},
		},
		Capability: manifest.ToolManifestCapability{
			TrustClass:  testToolTrustClass,
			RiskClass:   []string{testToolRiskClass},
			EffectClass: []string{testToolEffect},
		},
	}

	t.Run("non-zero exit code surfaces in Data", func(t *testing.T) {
		runner := &recordingRunner{exitCode: 1, stderr: "error occurred"}
		tool := subprocess.NewTool(*def, runner)
		result, err := tool.Execute(context.Background(), map[string]any{})
		require.NoError(t, err)
		require.False(t, result.Success)
		code, ok := result.Data["exit_code"]
		require.True(t, ok, "exit_code must be present in Data")
		require.Equal(t, 1, code)
	})

	t.Run("zero exit code surfaces exit_code=0", func(t *testing.T) {
		runner := &recordingRunner{exitCode: 0, stdout: "ok"}
		tool := subprocess.NewTool(*def, runner)
		result, err := tool.Execute(context.Background(), map[string]any{})
		require.NoError(t, err)
		require.True(t, result.Success)
		code, ok := result.Data["exit_code"]
		require.True(t, ok)
		require.Equal(t, 0, code)
	})

	t.Run("torn-down process has exit_code=-1", func(t *testing.T) {
		runner := &recordingRunner{exitCode: -1}
		tool := subprocess.NewTool(*def, runner)
		result, err := tool.Execute(context.Background(), map[string]any{})
		require.NoError(t, err)
		require.False(t, result.Success)
		code, ok := result.Data["exit_code"]
		require.True(t, ok)
		require.Equal(t, -1, code)
	})
}

func TestGenerateSubprocessTool_NoShellInjection(t *testing.T) {
	def := &manifest.ToolManifest{
		Name:   testToolName,
		Family: testToolFamily,
		Parameters: []manifest.ToolParameter{
			{Name: "value", Type: "string", Required: true},
		},
		Execution: manifest.ToolManifestExecution{
			Backend: manifest.ToolBackendSubprocess,
			Command: &manifest.ToolManifestCommand{
				Base: []string{"echo"},
				Args: []string{"${value}"},
			},
		},
		Capability: manifest.ToolManifestCapability{
			TrustClass:  "builtin_trusted",
			RiskClass:   []string{"execute"},
			EffectClass: []string{"external_state"},
		},
	}
	malicious := "hello; rm -rf /"
	runner := &recordingRunner{}
	tool := subprocess.NewTool(*def, runner)
	_, err := tool.Execute(context.Background(), map[string]any{"value": malicious})
	require.NoError(t, err)
	require.Len(t, runner.request.Args, 2)
	require.Equal(t, malicious, runner.request.Args[1])
}

func TestGenerateSubprocessTool_PlatformVariant(t *testing.T) {
	def := &manifest.ToolManifest{
		Name:   "demo",
		Family: "demo",
		Execution: manifest.ToolManifestExecution{
			Backend: manifest.ToolBackendSubprocess,
			Command: &manifest.ToolManifestCommand{
				Base: []string{"default"},
			},
			PlatformVariants: map[string]manifest.ToolManifestCommand{
				runtime.GOOS: {Base: []string{"variant"}},
			},
		},
		Capability: manifest.ToolManifestCapability{
			TrustClass:  "builtin_trusted",
			RiskClass:   []string{"execute"},
			EffectClass: []string{"external_state"},
		},
	}
	runner := &recordingRunner{}
	tool := subprocess.NewTool(*def, runner)
	_, err := tool.Execute(context.Background(), map[string]any{})
	require.NoError(t, err)
	require.Equal(t, []string{"variant"}, runner.request.Args)
}

func TestLoadPlatformConfig_UsesLocalToolPolicy(t *testing.T) {
	workspace := t.TempDir()
	require.NoError(t, writeWorkspaceToolFixture(workspace))

	cfg, err := LoadPlatformConfig(workspace)
	require.NoError(t, err)
	require.NotNil(t, cfg.ToolRegistry)
	require.NotEmpty(t, cfg.ToolRegistry.ListTools())
}

func TestBuildRegistry_RepositoryCorpus(t *testing.T) {
	repoRoot := filepath.Clean(filepath.Join("..", ".."))
	defs, err := LoadToolManifests(DefaultToolManifestDir(repoRoot))
	require.NoError(t, err)
	policy, err := security.LoadLocalToolPolicy("", repoRoot, StrictDecode)
	require.NoError(t, err)

	reg, err := BuildRegistry(defs, policy, nil, nil)
	require.NoError(t, err)
	require.NotNil(t, reg)
	require.NotEmpty(t, reg.ListTools())
	manifest, ok := reg.LookupTool("cli_git")
	require.True(t, ok)
	require.Equal(t, "cli_git", manifest.Name)
}

func writeWorkspaceToolFixture(workspace string) error {
	toolsDir := DefaultToolManifestDir(workspace)
	if err := fs.MkdirAllSecure(toolsDir); err != nil {
		return err
	}
	if err := fs.MkdirAllSecure(filepath.Join(workspace, "relurpify_cfg", "security")); err != nil {
		return err
	}
	if err := fs.WriteFileSecure(filepath.Join(toolsDir, "demo.tool.yaml"), []byte(`schema: relurpify/tool/v1
name: demo
family: demo
description: Demo tool
execution:
  backend: subprocess
  command:
    base: ["echo"]
capability:
  trust_class: builtin_trusted
  risk_class: [execute]
  effect_class: [external_state]
`)); err != nil {
		return err
	}
	return fs.WriteFileSecure(filepath.Join(workspace, "relurpify_cfg", "security", "localtool.policy.yaml"), []byte(`schema: relurpify/policy/localtool/v1
tools:
  demo:
    execute: ask
`))
}
