package registry

// DefaultToolNameNormalization maps common LLM tool name variations to their canonical
// capability names in the Relurpify platform.
var DefaultToolNameNormalization = map[string]string{
	// File Primitives (Contracts / FS)
	"read_file":                  "file_read",
	"view_file":                  "file_read",
	"cat":                        "file_read",
	"read":                       "file_read",
	"file_content":               "file_read",
	"get_file":                   "file_read",
	"read_file_content":          "file_read",
	"view_file_content":          "file_read",
	"readfile":                   "file_read",
	"show_file":                  "file_read",
	"display_file":               "file_read",
	"load_file":                  "file_read",
	"write_file":                 "file_write",
	"edit_file":                  "file_write",
	"file_edit":                  "file_write",
	"save_file":                  "file_write",
	"update_file":                "file_write",
	"str_replace_editor":         "file_write", // Anthropic-style file edit block
	"write_to_file":              "file_write",
	"write":                      "file_write",
	"patch_file":                 "file_write",
	"file_patch":                 "file_write",
	"edit":                       "file_write",
	"modify_file":                "file_write",
	"replace_file_content":       "file_write",
	"multi_replace_file_content": "file_write",
	"writefile":                  "file_write",
	"update":                     "file_write",
	"save":                       "file_write",
	"overwrite_file":             "file_write",
	"put_file":                   "file_write",
	"change_file":                "file_write",
	"list_dir":                   "file_list",
	"list_directory":             "file_list",
	"ls":                         "file_list",
	"dir":                        "file_list",
	"list":                       "file_list",
	"list_files":                 "file_list",
	"show_files":                 "file_list",
	"listfiles":                  "file_list",
	"view_directory":             "file_list",
	"read_directory":             "file_list",
	"scan_dir":                   "file_list",
	"search_file":                "file_search",
	"grep":                       "file_search",
	"ripgrep":                    "file_search",
	"rg":                         "file_search",
	"search_files":               "file_search",
	"find_files":                 "file_search",
	"find":                       "file_search",
	"file_grep":                  "file_search",
	"search":                     "file_search",
	"locate_files":               "file_search",
	"find_in_files":              "file_search",
	"create_file":                "file_create",
	"touch":                      "file_create",
	"new_file":                   "file_create",
	"create":                     "file_create",
	"add_file":                   "file_create",
	"createfile":                 "file_create",
	"make_file":                  "file_create",
	"mkfile":                     "file_create",
	"newfile":                    "file_create",
	"delete_file":                "file_delete",
	"remove_file":                "file_delete",
	"rm":                         "file_delete",
	"delete":                     "file_delete",
	"remove":                     "file_delete",
	"deletefile":                 "file_delete",
	"rmfile":                     "file_delete",
	"unlink":                     "file_delete",

	// Git Tools
	"git_show_changes":  "git_diff",
	"git_changes":       "git_diff",
	"show_diff":         "git_diff",
	"diff":              "git_diff",
	"gitdiff":           "git_diff",
	"git_log":           "git_history",
	"git_show_history":  "git_history",
	"log":               "git_history",
	"git_logs":          "git_history",
	"history":           "git_history",
	"githistory":        "git_history",
	"gitlog":            "git_history",
	"git_create_branch": "git_branch",
	"create_branch":     "git_branch",
	"branch":            "git_branch",
	"gitbranch":         "git_branch",
	"git_make_commit":   "git_commit",
	"commit":            "git_commit",
	"gitcommit":         "git_commit",
	"git_show_blame":    "git_blame",
	"blame":             "git_blame",
	"gitblame":          "git_blame",

	// Language Server Protocol (LSP)
	"get_definition":       "lsp_get_definition",
	"find_definition":      "lsp_get_definition",
	"go_to_definition":     "lsp_get_definition",
	"definition":           "lsp_get_definition",
	"goto_definition":      "lsp_get_definition",
	"lsp_definition":       "lsp_get_definition",
	"getdefinition":        "lsp_get_definition",
	"find_def":             "lsp_get_definition",
	"get_def":              "lsp_get_definition",
	"go_to_def":            "lsp_get_definition",
	"get_references":       "lsp_get_references",
	"find_references":      "lsp_get_references",
	"references":           "lsp_get_references",
	"lsp_references":       "lsp_get_references",
	"getreferences":        "lsp_get_references",
	"find_refs":            "lsp_get_references",
	"get_refs":             "lsp_get_references",
	"get_hover":            "lsp_get_hover",
	"hover":                "lsp_get_hover",
	"lsp_hover":            "lsp_get_hover",
	"hover_info":           "lsp_get_hover",
	"get_hover_info":       "lsp_get_hover",
	"hoverinfo":            "lsp_get_hover",
	"get_diagnostics":      "lsp_get_diagnostics",
	"diagnostics":          "lsp_get_diagnostics",
	"lsp_diagnostics":      "lsp_get_diagnostics",
	"get_errors":           "lsp_get_diagnostics",
	"errors":               "lsp_get_diagnostics",
	"diagnose":             "lsp_get_diagnostics",
	"getdiagnostics":       "lsp_get_diagnostics",
	"search_symbols":       "lsp_search_symbols",
	"find_symbols":         "lsp_search_symbols",
	"symbols":              "lsp_search_symbols",
	"workspace_symbols":    "lsp_search_symbols",
	"searchsymbols":        "lsp_search_symbols",
	"get_document_symbols": "lsp_document_symbols",
	"document_symbols":     "lsp_document_symbols",
	"file_symbols":         "lsp_document_symbols",
	"documentsymbols":      "lsp_document_symbols",
	"format":               "lsp_format",
	"format_file":          "lsp_format",
	"format_source":        "lsp_format",
	"code_format":          "lsp_format",
	"formatcode":           "lsp_format",

	// AST / Structural Analysis
	"ast_analyze":     "query_ast",
	"analyze_ast":     "query_ast",
	"ast_query":       "query_ast",
	"query_structure": "query_ast",
	"ast":             "query_ast",
	"astanalyze":      "query_ast",
	"queryast":        "query_ast",
	"get_ast":         "query_ast",
	"parse_ast":       "query_ast",

	// Execution & Verification Tasks
	"run_tests":       "exec_run_tests",
	"test":            "exec_run_tests",
	"pytest":          "exec_run_tests",
	"exec_test":       "exec_run_tests",
	"run_unit_tests":  "exec_run_tests",
	"execute_tests":   "exec_run_tests",
	"runtests":        "exec_run_tests",
	"go_test":         "exec_run_tests",
	"npm_test":        "exec_run_tests",
	"cargo_test":      "exec_run_tests",
	"rust_cargo_test": "exec_run_tests",
	"python_pytest":   "exec_run_tests",
	"run_code":        "exec_run_code",
	"execute_code":    "exec_run_code",
	"python":          "exec_run_code",
	"exec_code":       "exec_run_code",
	"run_command":     "exec_run_code",
	"execute_command": "exec_run_code",
	"cmd":             "exec_run_code",
	"runcode":         "exec_run_code",
	"eval":            "exec_run_code",
	"exec_command":    "exec_run_code",
	"run_linter":      "exec_run_linter",
	"lint":            "exec_run_linter",
	"execute_linter":  "exec_run_linter",
	"run_lint":        "exec_run_linter",
	"runlinter":       "exec_run_linter",
	"code_lint":       "exec_run_linter",
	"run_build":       "exec_run_build",
	"build":           "exec_run_build",
	"compile":         "exec_run_build",
	"execute_build":   "exec_run_build",
	"runbuild":        "exec_run_build",
	"make":            "exec_run_build",
	"go_build":        "exec_run_build",

	// Search & Semantic Queries
	"grep_search":       "search_grep",
	"ripgrep_search":    "search_grep",
	"regex_search":      "search_grep",
	"text_search":       "search_grep",
	"grepsearch":        "search_grep",
	"find_similar":      "search_find_similar",
	"similarity_search": "search_find_similar",
	"find_similar_code": "search_find_similar",
	"similar_code":      "search_find_similar",
	"findsimilar":       "search_find_similar",
	"semantic_search":   "search_semantic",
	"vector_search":     "search_semantic",
	"concept_search":    "search_semantic",
	"semanticsearch":    "search_semantic",
}

func DefaultToolName(name string) (string, bool) {
	canonical, ok := DefaultToolNameNormalization[name]
	return canonical, ok
}
