// Code generated by toolgen; DO NOT EDIT.
package search

import (
	"fmt"
	"strings"
)

// SearchGrepParams holds the typed parameters for this tool.
type SearchGrepParams struct {
	Pattern   string `json:"pattern"`
	Directory string `json:"directory,omitempty"`
}

// ParseSearchGrepParams reads typed parameter values from a map[string]interface{}.
func ParseSearchGrepParams(args map[string]interface{}) (SearchGrepParams, error) {
	var p SearchGrepParams
	var errs []string

	if v, ok := args["pattern"]; ok && v != nil {
		val, err := convString("pattern", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Pattern = val
		}
	} else {
		errs = append(errs, "missing required parameter \"pattern\"")
	}

	if v, ok := args["directory"]; ok && v != nil {
		val, err := convString("directory", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Directory = val
		}
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// SearchGrepParamKeys returns the parameter names this tool consumes.
func SearchGrepParamKeys() []string {
	return []string{
		"pattern",
		"directory",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
