// Code generated by toolgen; DO NOT EDIT.
package search

import (
	"fmt"
	"strings"
)

// SearchFindSimilarParams holds the typed parameters for this tool.
type SearchFindSimilarParams struct {
	Snippet   string `json:"snippet"`
	Directory string `json:"directory,omitempty"`
}

// ParseSearchFindSimilarParams reads typed parameter values from a map[string]interface{}.
func ParseSearchFindSimilarParams(args map[string]interface{}) (SearchFindSimilarParams, error) {
	var p SearchFindSimilarParams
	var errs []string

	if v, ok := args["snippet"]; ok && v != nil {
		val, err := convString("snippet", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Snippet = val
		}
	} else {
		errs = append(errs, "missing required parameter \"snippet\"")
	}

	if v, ok := args["directory"]; ok && v != nil {
		val, err := convString("directory", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Directory = val
		}
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// SearchFindSimilarParamKeys returns the parameter names this tool consumes.
func SearchFindSimilarParamKeys() []string {
	return []string{
		"snippet",
		"directory",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
