// Code generated by toolgen; DO NOT EDIT.
package search

import (
	"fmt"
	"strings"
)

// SearchSemanticParams holds the typed parameters for this tool.
type SearchSemanticParams struct {
	Query string `json:"query"`
}

// ParseSearchSemanticParams reads typed parameter values from a map[string]interface{}.
func ParseSearchSemanticParams(args map[string]interface{}) (SearchSemanticParams, error) {
	var p SearchSemanticParams
	var errs []string

	if v, ok := args["query"]; ok && v != nil {
		val, err := convString("query", v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			p.Query = val
		}
	} else {
		errs = append(errs, "missing required parameter \"query\"")
	}

	if len(errs) > 0 {
		return p, fmt.Errorf("parameter errors: %s", strings.Join(errs, "; "))
	}
	return p, nil
}

// SearchSemanticParamKeys returns the parameter names this tool consumes.
func SearchSemanticParamKeys() []string {
	return []string{
		"query",
	}
}

// convString, convInt64, convFloat64, convBool, convSliceInterface,
// convMapStringInterface are generated in toolgen_helpers.gen.go.
