// Code generated by toolgen; DO NOT EDIT.

package search

import (
	"fmt"
	"strconv"
	"strings"
)

func convString(name string, v interface{}) (string, error) {
	return fmt.Sprint(v), nil
}

func convInt64(name string, v interface{}) (int64, error) {
	switch val := v.(type) {
	case int64:
		return val, nil
	case float64:
		return int64(val), nil
	case int:
		return int64(val), nil
	case string:
		n, err := strconv.ParseInt(strings.TrimSpace(val), 10, 64)
		if err != nil {
			return 0, fmt.Errorf("parameter %q: %w", name, err)
		}
		return n, nil
	default:
		return 0, fmt.Errorf("parameter %q: expected integer, got %T", name, v)
	}
}

func convFloat64(name string, v interface{}) (float64, error) {
	switch val := v.(type) {
	case float64:
		return val, nil
	case int64:
		return float64(val), nil
	case int:
		return float64(val), nil
	case string:
		n, err := strconv.ParseFloat(strings.TrimSpace(val), 64)
		if err != nil {
			return 0, fmt.Errorf("parameter %q: %w", name, err)
		}
		return n, nil
	default:
		return 0, fmt.Errorf("parameter %q: expected number, got %T", name, v)
	}
}

func convBool(name string, v interface{}) (bool, error) {
	switch val := v.(type) {
	case bool:
		return val, nil
	case string:
		b, err := strconv.ParseBool(strings.TrimSpace(val))
		if err != nil {
			return false, fmt.Errorf("parameter %q: %w", name, err)
		}
		return b, nil
	default:
		return false, fmt.Errorf("parameter %q: expected boolean, got %T", name, v)
	}
}

func convSliceInterface(name string, v interface{}) ([]interface{}, error) {
	switch val := v.(type) {
	case []interface{}:
		return val, nil
	default:
		return nil, fmt.Errorf("parameter %q: expected array, got %T", name, v)
	}
}

func convMapStringInterface(name string, v interface{}) (map[string]interface{}, error) {
	switch val := v.(type) {
	case map[string]interface{}:
		return val, nil
	default:
		return nil, fmt.Errorf("parameter %q: expected object, got %T", name, v)
	}
}
